<script src="{{ asset('backend/vendor/jquery.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="{{ asset('backend/vendor/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('backend/vendor/dom-factory.js') }}"></script>
<script src="{{ asset('backend/vendor/material-design-kit.js') }}"></script>
<script src="{{ asset('backend/js/toggle-check-all.js') }}"></script>
<script src="{{ asset('backend/js/check-selected-row.js') }}"></script>
<script src="{{ asset('backend/js/dropdown.js') }}"></script>
<script src="{{ asset('backend/js/sidebar-mini.js') }}"></script>
<script src="{{ asset('backend/js/app.js') }}"></script>
<!-- <script src="{{ asset('backend/vendor/flatpickr/flatpickr.min.js') }}"></script> -->
<script src="{{ asset('backend/js/flatpickr.js') }}"></script>
<script src="{{ asset('backend/js/settings.js') }}"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
